export const ERR_NOT_FOUND_EVENTS = 'ERR_NOT_FOUND_EVENTS';
export const ERR_NOT_FOUND_EVENT = 'ERR_NOT_FOUND_EVENT';
export const ERR_USER_NOT_ACTIVATED = 'ERR_USER_NOT_ACTIVATED';
export const ERR_NOT_FOUND_BROWSER_SERVICE = 'ERR_NOT_FOUND_BROWSER_SERVICE';
export const ERR_EMAIL_NOT_FOUND = 'ERR_EMAIL_NOT_FOUND';
export const ERR_EMAIL_ALREADY_EXIST = 'ERR_EMAIL_ALREADY_EXIST';
export const ERR_NOT_FOUND_USER = 'ERR_NOT_FOUND_USER';
export const ERR_EXPIRED_CODE = 'ERR_EXPIRED_CODE';
export const ERR_10_MAX_ATTACHMENT_IN_EVENT_CODE =
  'ERR_10_MAX_ATTACHMENT_IN_EVENT_CODE';
export const EMAIL_OR_PASSWORD_IS_INCORRECT = 'EMAIL_OR_PASSWORD_IS_INCORRECT';
export const ERR_SEND_MAIL = 'ERR_SEND_MAIL';

export const ERR_UPLOAD_FAILED = 'ERR_UPLOAD_FAILED';
export const ERR_PAYMENT_INTENT_FAILED = 'ERR_CHECKOUT_FAILED';
export const ERR_REFUND_CANT_BE_REQUESTED = 'ERR_REFUND_CANT_BE_REQUESTED';
export const ERR_NOT_FOUND_ATTACHMENTS = 'ERR_NOT_FOUND_ATTACHMENTS';
export const ERR_PRIMARY_ATTACHMENTS_NOT_FOUND = 'ERR_PRIMARY_ATTACHMENTS_NOT_FOUND';

export const ERR_PAYMENT = 'ERR_PAYMENT';
export const ERR_DESTINATION_NOT_ALLOWED_TO_ORDER = 'ERR_DESTINATION_NOT_ALLOWED_TO_ORDER';
export const ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN';
export const ERR_LABEL_NOT_FOUND = 'ERR_LABEL_NOT_FOUND';
export const ERR_NOT_FOUND_DESTINATIONS = 'ERR_NOT_FOUND_DESTINATIONS';
export const ERR_NOT_FOUND_CATEGORY = 'ERR_NOT_FOUND_CATEGORY';
export const Unauthorized = 'Unauthorized';
export const ONLY_ADMINS_HAVE_ACCESS_TO_THIS_PLACE = 'ONLY_ADMINS_HAVE_ACCESS_TO_THIS_PLACE';
export const ERR_ORDER_ALREADY_REFUNDED = 'ERR_ORDER_ALREADY_REFUNDED';
export const ERR_NOT_FOUND_ORDER = 'ERR_NOT_FOUND_ORDER';
export const ERROR_MAX_PARTICIPANTS_GRATER_REQUIRED = 'ERROR_MAX_PARTICIPANTS_GRATER_REQUIRED';
export const ERROR_START_DATE_GRATER_END_DATE = 'ERROR_START_DATE_GRATER_END_DATE';
